[.text-justify]
= Dock AEM
:reproducible:
:doctype: article
:author: Herman Ciechanowiec
:email: herman@ciechanowiec.eu
:chapter-signifier:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:toc: left
:toclevels: 5
:icons: font
// Docinfo is used for foldable TOC.
// -> For full usage example see https://github.com/remkop/picocli
:docinfo: shared,private
:linkcss:
:stylesdir: https://www.ciechanowiec.eu/linux_mantra/
:stylesheet: adoc-css-style.css

== Overview

_Dock AEM_ is a program for setting up and managing local Adobe Experience Manager (AEM) development environment via Docker. It provides ready-to-go tools for swift bootstrapping and controlling interconnected AEM Author, AEM Publish, and AEM Dispatcher/Varnish Cache instances. The program supports both on-premise (AEM 6.5) and cloud (AEMaaCS) versions of Adobe Experience Manager.

== Usage
_Dock AEM_ provides a `docker-compose.yml` file and related artifacts, enabling developers to:
[upperalpha]
. build various AEM images
. run, start, and stop AEM containers

Supported images include:
[upperalpha]
. AEM Author 6.5
. AEM Author as a Cloud Service
. AEM Publish 6.5
. AEM Publish as a Cloud Service
. AEM Dispatcher for AMD CPU architecture
. AEM Dispatcher for ARM CPU architecture
. Varnish Cache

=== Images Build

==== Steps
In order to build the _Dock AEM_ images follow the steps below.

[upperalpha]
. Clone the _Dock AEM_ source code repository:
+
[source, bash]
----
git clone https://github.com/ciechanowiec/dock_aem
----

. Remove all preceding _Dock AEM_ containers, images and volumes:
+
[source, bash]
----
artifactsToRemove="aem-base aem-author-65 aem-author-cloud aem-publish-65 aem-publish-cloud dispatcher-amd dispatcher-arm varnish"

docker container stop --time 30 "$artifactsToRemove"

docker container remove --force "$artifactsToRemove"

docker image remove --force "$artifactsToRemove"

docker volume remove --force aem-author-65-data aem-author-cloud-data aem-publish-65-data aem-publish-cloud-data
----

. `license.properties`
+
Put a `license.properties` file into `src/commons` directory. It will be used during the build for both AEM 6.5 and AEMaaCS.

. `src/quickstart`
+
Put respective AEM QuickStart Jars into `src/quickstart/65` (AEM 6.5) and `src/quickstart/cloud` (AEMaaCS) directories in the _Dock AEM_ source code repository (files inside those directories are git-ignored, so there is no relevant risk of exposing them in the source control). Give both those Jars the following name: `aem-quickstart.jar`.

. `src/packages`
+
If there are any packages that should be preinstalled on AEM Author and AEM Publish, put them respectively into `src/packages/65` (AEM 6.5) or `src/packages/cloud` (AEMaaCS) directories in the _Dock AEM_ source code repository (files inside those directories, just like the files inside `src/quickstart` subdirectories, are git-ignored, so there is no relevant risk of exposing them in the source control).
+
For instance, into `src/packages/65` the following packages can be put:
[upperroman]
.. `aem-service-pkg-6.5.16-NPR-40551-B002.zip` (AEM Service Pack 6.5.16)
.. `adobe-aemfd-linux-pkg-6.0.914.zip` (AEM Forms Addon related to AEM 6.5.16)
.. `content.zip` (preinstalled content)

+

The `src/packages/cloud` directory, in turn, can be populated with the following packages:
[upperroman]
.. `aem-forms-addon-2023.08.03.00-230800.far` (AEM Forms Addon related to AEMaaCS)
.. `content.zip` (preinstalled content)

. `src/commons/crypto`
+
An `src/commons/crypto` directory contains a `data` directory with default `hmac` and `master` keys. Those keys are used by `com.adobe.granite.crypto.file` bundle for secrets encoding and default versions of the keys are provided for deterministic and predictable behavior. If it is necessary to use different keys, replace the existing ones with the new ones. However, note that those keys aren't git-ignored, so be careful and don't git commit sensitive secrets.

. During the images build, AEM Author and AEM Publish instances are started. Among others, this is done in order to initialize persistence layer and reduce the amount of time required for the first clean start of containers based on the built images. The start of AEM Author and AEM Publish is controlled by `src/2_aem/aem-starter.sh` script. That script also shutdowns the instances once the initialization is finished.
+
The initialization is assumed to be finished when all required bundles have started and are active. The amount of required bundles might differ depending on the exact set of preinstalled packages from `src/packages`, on run mode choice (`author`/`publish`, `samplecontent`/`nosamplecontent`) and the subsequent number of an instance start.
+

.Expected bundles status for selected AEM setups
[cols="4,2,2"]
|===
| |First Start |Second and Subsequent Starts
| _AEM 6.5_ +
- author/publish +
- nosamplecontent +
- aem-service-pkg-6.5.16-NPR-40551-B002.zip +
- adobe-aemfd-linux-pkg-6.0.914.zip
|719
|725

| _AEMaaCS_ +
- author +
- nosamplecontent +
- aem-sdk-quickstart-2023.8.13206.20230821T124823Z-230800.jar +
- aem-forms-addon-2023.08.03.00-230800.far
|676
|676

| _AEMaaCS_ +
- publish +
- nosamplecontent +
- aem-sdk-quickstart-2023.8.13206.20230821T124823Z-230800.jar +
- aem-forms-addon-2023.08.03.00-230800.far
|670
|670
|===
+
Due to the bundles readiness check described above, the exact expected amount of active bundles for the specified AEM setups must be configured in the `docker-compose.yml` file.

. Go to `src` directory in the _Dock AEM_ source code repository. Inside that directory, run the build defined in the `docker-compose.yml` file. As a result, eight images will be built: `aem-base`, `aem-author-65`, `aem-author-cloud`, `aem-publish-65`, `aem-publish-cloud`, `dispatcher-amd`, `dispatcher-arm` and `varnish`. For fully fledged AEM instances the build might take ~45 minutes in total, depending on hardware capabilities:
+
[source, bash]
----
cd "$pathToDockAEMSourceCodeRepository/src"

docker compose build
----
+
[NOTE]
====
[upperroman]
. In case of certain system setups, the command above should be hyphenated: `docker-compose`.
. Add `--progress=plain` to the above command to see unfolded build output:
+
[source, bash]
----
docker compose --progress=plain build
----
. It is possible to build independently only some specific image defined the `docker-compose.yml` file by providing that image name to the build command in the following way:
+
[source, bash]
----
docker compose build aem-author-cloud
----
====

. Verify the build and make sure that all eight _Dock AEM_ images are available on host:
+
[source, bash]
----
❯ docker images
REPOSITORY          TAG       IMAGE ID       CREATED      SIZE
aem-base            latest    ebf85dfbc09a   1 hour ago   867MB
aem-author-65       latest    10e7e329a513   1 hour ago   9.66GB
aem-author-cloud    latest    69180e29fbaf   1 hour ago   3.81GB
aem-publish-65      latest    0de503a9527c   1 hour ago   9.59GB
aem-publish-cloud   latest    b363142f9fde   1 hour ago   3.71GB
dispatcher-amd      latest    1d3fe5004212   1 hour ago   332MB
dispatcher-arm      latest    67f57547c3fa   1 hour ago   332MB
varnish             latest    c09dd5353890   1 hour ago   298MB
----

=== Container Run, Start & Stop
[upperalpha]
. All containers based on the _Dock AEM_ images can be run, started and stopped independently.
. In order to run a given container for the first time, use the `docker-compose.yml` file located inside `src` directory in the _Dock AEM_ source code repository:
+
[source, bash]
----
# AEM Author 6.5:
docker compose up aem-author-65 --detach

# AEM Author Cloud:
docker compose up aem-author-cloud --detach

# AEM Publish 6.5:
docker compose up aem-publish-65 --detach

# AEM Publish Cloud:
docker compose up aem-publish-cloud --detach

# AEM Dispatcher AMD:
docker compose up dispatcher-amd --detach

# AEM Dispatcher ARM:
docker compose up dispatcher-arm --detach

# Varnish Cache:
docker compose up varnish --detach
----
+
[NOTE]
In case of certain system setups, the command above should be hyphenated: `docker-compose`.

. After the first run a given container can be started and stopped via regular Docker commands:
+
[source, bash]
----
# AEM Author 6.5:
docker start aem-author-65
docker stop aem-author-65

# AEM Author as a Cloud Service:
docker start aem-author-cloud
docker stop aem-author-cloud

# AEM Publish 6.5:
docker start aem-publish-65
docker stop aem-publish-65

# AEM Publish as a Cloud Service:
docker start aem-publish-cloud
docker stop aem-publish-cloud

# AEM Dispatcher for AMD CPU architecture:
docker start dispatcher-amd
docker stop dispatcher-amd

# AEM Dispatcher for ARM CPU architecture:
docker start dispatcher-arm
docker stop dispatcher-arm

# Varnish Cache:
docker start varnish
docker stop varnish
----

=== AEM Dispatcher & Varnish Cache Specifics
[upperalpha]
. AEM Dispatcher and Varnish Cache configuration files used during images build are the default ones, but adjusted as little as possible according to the official instructions. The original versions of the configuration files for the sake of comparison are kept in respective directories besides the changed ones.
. In order to transfer files (primarily new configuration files) from the host into a container in which AEM Dispatcher or Varnish Cache are run, use commands constructed in the following way:
+
[source, bash]
----
# AEM Dispatcher - AMD:
docker cp "$HOME/dispatcher.any" dispatcher-amd:/etc/apache2/conf/dispatcher.any

# AEM Dispatcher - ARM:
docker cp "$HOME/dispatcher.any" dispatcher-arm:/etc/apache2/conf/dispatcher.any

# Varnish Cache:
docker cp "$HOME/default.vcl" varnish:/etc/varnish/default.vcl
----

. In order to activate new configuration of AEM Dispatcher or Varnish Cache, there is no need to restart containers. New configuration can be applied via reloading:
+
[source, bash]
----
# AEM Dispatcher - AMD:
docker exec dispatcher-amd /etc/init.d/apache2 reload

# AEM Dispatcher - ARM:
docker exec dispatcher-arm /etc/init.d/apache2 reload

# Varnish Cache:
docker exec varnish varnishreload
----

=== Mobile Volumes
[upperalpha]
. Persistence layers of AEM Author and AEM Publish instances are linked to `/opt/aem/author/crx-quickstart` and `/opt/aem/publish/crx-quickstart` paths inside respective containers. Those paths are mount points for `aem-author-data-65`, `aem-author-data-cloud`, `aem-publish-data-65` and `aem-publish-data-cloud` volumes respectively, physically stored on a host at `/var/lib/docker/volumes` and managed by Docker. It means that persistence layers of AEM Author and AEM Publish instances are separated from the application.

. If `aem-author-data-65`, `aem-author-data-cloud`, `aem-publish-data-65` or `aem-publish-data-cloud` volume doesn't exist when a container with AEM Author or AEM Publish respectively is run for the first time, then a respective volume will be created and mounted to the container. However, if a respective volume does already exist, then no new volume will be created and the existing one will be reused, so that even to a new container the old volume with old persistence layer will be mounted. In order to avoid such reuse, before a new container is run for the first time, the respective volume should be priorly removed:
+
[source, bash]
----
# AEM Author 6.5:
docker volume remove --force aem-author-data-65

# AEM Author as a Cloud Service:
docker volume remove --force aem-author-data-cloud

# AEM Publish 6.5:
docker volume remove --force aem-publish-data-65

# AEM Publish as a Cloud Service:
docker volume remove --force aem-publish-data-cloud
----

. The described volumes mechanism makes AEM Author and AEM Publish persistence layers mobile, transferable and backupable. That mechanism can be rolled out to remote environments in order to make those environments fully reproducible locally.

== Start Command Decomposition
This section explains every part of commands used to start AEM instances. The explanation employs an example based on the command for the AEM Author, but nevertheless for AEM Publish the command is analogous.

[upperalpha]
. Set max heap size:
+
`-Xmx4096M`
+
_Docs:_ +
https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/deploy.html?lang=en (`-Xmx1024M` is given as recommended, but it is too little for parallel garbage collection)

. Fix Java 11 bug related to ZIP validation:
+
`-Djdk.util.zip.disableZip64ExtraFieldValidation=true`
+
_Docs:_ +
[upperroman]
.. https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/aem-local-server-error-while-starting/m-p/613644/highlight/true#M153985
.. https://liferay.atlassian.net/browse/LPS-191551

. Run AEM in a headless mode because it is run inside a Docker container:
+
`-Djava.awt.headless=true`

. Set JVM specific parameters for Java 11:
+
`-XX:+UseParallelGC --add-opens=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED --add-opens=java.base/sun.net.www.protocol.jrt=ALL-UNNAMED --add-opens=java.naming/javax.naming.spi=ALL-UNNAMED --add-opens=java.xml/com.sun.org.apache.xerces.internal.dom=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED -Dnashorn.args=--no-deprecation-warning`
+
_Docs:_ +
https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/custom-standalone-install.html?lang=en

. Run AEM in debug mode on the given port, additionally to the basic port:
+
`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888`
+
_Docs:_ +
https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/debugging/debugging-aem-sdk/remote-debugging.html?lang=en

. Set initial admin password in non-interactive mode. The admin password from
a `passwordfile.properties` file is assessed only during the first AEM start. If after the first AEM start the admin password is changed, the new password is effective regardless of the content of a `passwordfile.properties` file:
+
`-Dadmin.password.file=/opt/aem/author/passwordfile.properties` +
(...) +
`-nointeractive`
+
_Docs:_ +
https://experienceleague.adobe.com/docs/experience-manager-65/administering/security/security-configure-admin-password.html?lang=en

. Set run modes:
+
`-Dsling.run.modes=author,nosamplecontent,local`
+
_Docs:_ +
https://experienceleague.adobe.com/docs/experience-manager-65/deploying/configuring/configure-runmodes.html?lang=en

. Set port:
+
`-port 4502`
+
_Docs:_ +
https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/custom-standalone-install.html?lang=en

. Exclude forks (among others, it mitigates warnings in the console):
+
`-nofork`
+
_Docs:_ +
https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/custom-standalone-install.html?lang=en

. Don't open AEM in a browser, since AEM is run inside a Docker container:
+
`-nobrowser`
+
_Docs:_ +
https://experienceleague.adobe.com/docs/experience-manager-65/deploying/deploying/custom-standalone-install.html?lang=en

== License
The program is subject to MIT No Attribution License

Copyright © 2023 Herman Ciechanowiec

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

The Software is provided 'as is', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the Software or the use or other dealings in the Software.
