version: "3.9"

services:
  aem-author:
    container_name: aem-author
    image: aem-author:latest
    volumes:
      - type: volume
        source: aem-author-data
        target: /opt/aem/author/crx-quickstart
    command: [ "java",
               "-Xmx4096M",
               "-Djava.awt.headless=true",
               "-XX:+UseParallelGC", "--add-opens=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED", "--add-opens=java.base/sun.net.www.protocol.jrt=ALL-UNNAMED", "--add-opens=java.naming/javax.naming.spi=ALL-UNNAMED", "--add-opens=java.xml/com.sun.org.apache.xerces.internal.dom=ALL-UNNAMED", "--add-opens=java.base/java.lang=ALL-UNNAMED", "--add-opens=java.base/jdk.internal.loader=ALL-UNNAMED", "--add-opens=java.base/java.net=ALL-UNNAMED", "-Dnashorn.args=--no-deprecation-warning",
               "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888",
               "-Dadmin.password.file=/opt/aem/author/passwordfile.properties",
               "-Dsling.run.modes=author,nosamplecontent,local",
               "-jar", "/opt/aem/author/aem-quickstart-6.5.0.jar",
               "-nointeractive",
               "-port", "4502",
               "-nofork",
               "-nobrowser" ]
    #   AEM is started for the first time during the image build, hence passing
    #   the password file during container startup is idle. However, the following
    #   secrets section is retained in case the image build definition changes:
    #    secrets:
    #      - source: admin-password
    #        target: /opt/aem/author/passwordfile.properties
    #        mode: 0444
    network_mode: "host"
    #   In case of `network_mode` set to `host` ports publishing should be disabled:
#    ports:
#      - target: 4502
#        published: 4502
#
#      - target: 8888
#        published: 8888
#    networks:
#      - aem

# See the comment above on secrets
#secrets:
#  admin-password:
#    file: 2_author/passwordfile.properties

volumes:
  aem-author-data:
    name: "aem-author-data"

# See the comment above on ports publishing
#networks:
#  aem:
#    name: aem
