version: "3.9"

services:
  varnish:
    container_name: varnish
    image: varnish:latest
    network_mode: "host"
    #   In case of `network_mode` set to `host` ports publishing should be disabled:
#    ports:
#      - target: 80
#        published: 80
#    networks:
#      - aem

# See the comment above on ports publishing
#networks:
#  aem:
#    name: aem
