version: "3.9"

x-custom-variables:
  &global-variables
  AEM_PUBLISH_HOSTNAME: aem-publish
  DISPATCHER_HOSTNAME: dispatcher

services:
  aem-base:
    build:
      context: .
      dockerfile: 1_base/Dockerfile
    image: aem-base:latest
    hostname: aem-base
    networks:
      - aem-network

  aem-author-65:
    build:
      context: .
      dockerfile: 2_aem/Dockerfile
      args:
        <<: *global-variables
        AEM_DIR: /opt/aem/author
        AEM_TYPE: 65
        RUN_MODES: author,nosamplecontent,local
        AEM_PORT: 4502
        DEBUG_PORT: 8888
        NUM_OF_EXPECTED_BUNDLES_AFTER_FIRST_START: 719
        NUM_OF_EXPECTED_BUNDLES_AFTER_SECOND_AND_SUBSEQUENT_STARTS: 725
    environment:
      AEM_DIR: /opt/aem/author
      AEM_TYPE: 65
      RUN_MODES: author,nosamplecontent,local
      AEM_PORT: 4502
      DEBUG_PORT: 8888
    image: aem-author-65:latest
    container_name: aem-author-65
    volumes:
      - type: volume
        source: aem-author-65-data
        target: /opt/aem/author/crx-quickstart
    entrypoint: ["sh", "-c", "$$AEM_DIR/aem-starter.sh" ]
    hostname: aem-author
    networks:
      - aem-network
    ports:
      - target: 4502
        published: 4502
        protocol: tcp
        mode: host
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
    depends_on:
      - aem-base

  aem-author-cloud:
    build:
      context: .
      dockerfile: 2_aem/Dockerfile
      args:
        <<: *global-variables
        AEM_DIR: /opt/aem/author
        AEM_TYPE: cloud
        RUN_MODES: author,nosamplecontent,local,author-local
        AEM_PORT: 4502
        DEBUG_PORT: 8888
        NUM_OF_EXPECTED_BUNDLES_AFTER_FIRST_START: 683
        NUM_OF_EXPECTED_BUNDLES_AFTER_SECOND_AND_SUBSEQUENT_STARTS: 683
    environment:
      AEM_DIR: /opt/aem/author
      AEM_TYPE: cloud
      RUN_MODES: author,nosamplecontent,local
      AEM_PORT: 4502
      DEBUG_PORT: 8888
    image: aem-author-cloud:latest
    container_name: aem-author-cloud
    volumes:
      - type: volume
        source: aem-author-cloud-data
        target: /opt/aem/author/crx-quickstart
    entrypoint: ["sh", "-c", "$$AEM_DIR/aem-starter.sh" ]
    hostname: aem-author
    networks:
      - aem-network
    ports:
      - target: 4502
        published: 4502
        protocol: tcp
        mode: host
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
    depends_on:
      - aem-base

  aem-publish-65:
    build:
      context: .
      dockerfile: 2_aem/Dockerfile
      args:
        <<: *global-variables
        AEM_DIR: /opt/aem/publish
        AEM_TYPE: 65
        RUN_MODES: publish,nosamplecontent,local
        AEM_PORT: 4503
        DEBUG_PORT: 8889
        NUM_OF_EXPECTED_BUNDLES_AFTER_FIRST_START: 719
        NUM_OF_EXPECTED_BUNDLES_AFTER_SECOND_AND_SUBSEQUENT_STARTS: 725
    environment:
      AEM_DIR: /opt/aem/publish
      AEM_TYPE: 65
      RUN_MODES: publish,nosamplecontent,local,publish-local
      AEM_PORT: 4503
      DEBUG_PORT: 8889
    image: aem-publish-65:latest
    container_name: aem-publish-65
    volumes:
      - type: volume
        source: aem-publish-65-data
        target: /opt/aem/publish/crx-quickstart
    entrypoint: ["sh", "-c", "$$AEM_DIR/aem-starter.sh" ]
    hostname: aem-publish
    networks:
      - aem-network
    ports:
      - target: 4503
        published: 4503
        protocol: tcp
        mode: host
      - target: 8889
        published: 8889
        protocol: tcp
        mode: host
    depends_on:
      - aem-base

  aem-publish-cloud:
    build:
      context: .
      dockerfile: 2_aem/Dockerfile
      args:
        <<: *global-variables
        AEM_DIR: /opt/aem/publish
        AEM_TYPE: cloud
        RUN_MODES: publish,nosamplecontent,local
        AEM_PORT: 4503
        DEBUG_PORT: 8889
        NUM_OF_EXPECTED_BUNDLES_AFTER_FIRST_START: 677
        NUM_OF_EXPECTED_BUNDLES_AFTER_SECOND_AND_SUBSEQUENT_STARTS: 677
    environment:
      AEM_DIR: /opt/aem/publish
      AEM_TYPE: cloud
      RUN_MODES: publish,nosamplecontent,local
      AEM_PORT: 4503
      DEBUG_PORT: 8889
    image: aem-publish-cloud:latest
    container_name: aem-publish-cloud
    volumes:
      - type: volume
        source: aem-publish-cloud-data
        target: /opt/aem/publish/crx-quickstart
    entrypoint: ["sh", "-c", "$$AEM_DIR/aem-starter.sh" ]
    hostname: aem-publish
    networks:
      - aem-network
    ports:
      - target: 4503
        published: 4503
        protocol: tcp
        mode: host
      - target: 8889
        published: 8889
        protocol: tcp
        mode: host
    depends_on:
      - aem-base

  dispatcher-amd:
    build:
      context: .
      dockerfile: 3_dispatcher/Dockerfile
      args:
        <<: *global-variables
        CPU_ARCH: x86_64
    image: dispatcher-amd:latest
    container_name: dispatcher-amd
    hostname: dispatcher
    networks:
      - aem-network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - aem-base

  dispatcher-arm:
    build:
      context: .
      dockerfile: 3_dispatcher/Dockerfile
      args:
        <<: *global-variables
        CPU_ARCH: aarch64
    image: dispatcher-arm:latest
    container_name: dispatcher-arm
    hostname: dispatcher
    networks:
      - aem-network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - aem-base

  varnish:
    build:
      context: .
      dockerfile: 4_varnish/Dockerfile
      args:
        <<: *global-variables
    image: varnish:latest
    container_name: varnish
    hostname: varnish
    networks:
      - aem-network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - aem-base

  solr:
    build:
      context: .
      dockerfile: 5_solr/Dockerfile
      args:
        SOLR_DIR: /opt/solr
        ZOOKEEPER_HOSTNAME: zookeeper
        ZOOKEEPER_PORT: 2181
        IS_UNSAFE: true
    environment:
      SOLR_DIR: /opt/solr
      SOLR_PORT: 8983
    image: solr:latest
    container_name: solr
    entrypoint: ["sh", "-c", "$$SOLR_DIR/solr-starter.sh" ]
    hostname: solr
    networks:
      - aem-network
    ports:
      - target: 8983
        published: 8983
        protocol: tcp
        mode: host
    depends_on:
      - aem-base
      - zookeeper

  zookeeper:
    build:
      context: .
      dockerfile: 6_zookeeper/Dockerfile
      args:
        ZOOKEEPER_DIR: /opt/zookeeper
        ZOOKEEPER_MY_ID: "1"
    environment:
      ZOOKEEPER_DIR: /opt/zookeeper
    image: zookeeper:latest
    container_name: zookeeper
    entrypoint: ["sh", "-c", "$$ZOOKEEPER_DIR/zookeeper-starter.sh" ]
    hostname: zookeeper
    networks:
      - aem-network
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    depends_on:
      - aem-base

volumes:
  aem-author-65-data:
    name: "aem-author-65-data"
  aem-author-cloud-data:
    name: "aem-author-cloud-data"
  aem-publish-65-data:
    name: "aem-publish-65-data"
  aem-publish-cloud-data:
    name: "aem-publish-cloud-data"

networks:
  aem-network:
    driver: bridge
