name: 'Release AEM Base'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Verify Docker Push Permissions
        run: |
          docker pull alpine:latest
          docker tag alpine:latest ${{ secrets.DOCKERHUB_USERNAME }}/test-push:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-push:latest
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/test-push:latest || true
      - name: Build and Push AEM Base JVM 11
        run: |
          cd src
          docker buildx create --use
          docker buildx bake \
            --file docker-compose.yml \
            --set aem-base-jvm11.platform=linux/amd64,linux/arm64 \
            --push \
            aem-base-jvm11
      - name: Build and Push AEM Base JVM 21
        run: |
          cd src
          docker buildx create --use
          docker buildx bake \
            --file docker-compose.yml \
            --set aem-base-jvm21.platform=linux/amd64,linux/arm64 \
            --push \
            aem-base-jvm21
